# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/chees_000/Documents/Programs/CSM51A/Project3/Project3.cache/wt [current_project]
set_property parent.project_path C:/Users/chees_000/Documents/Programs/CSM51A/Project3/Project3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/chees_000/Documents/Programs/CSM51A/Project3/Project3.srcs/sources_1/new/jkff.v
  C:/Users/chees_000/Documents/Programs/CSM51A/Project3/Project3.srcs/sources_1/new/csm51a_proj3.v
  C:/Users/chees_000/Documents/Programs/CSM51A/Project3/Project3.srcs/sources_1/new/csm51a_proj3_tb.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top csm51a_proj3_tb -part xc7k70tfbv676-1


write_checkpoint -force -noxdef csm51a_proj3_tb.dcp

catch { report_utilization -file csm51a_proj3_tb_utilization_synth.rpt -pb csm51a_proj3_tb_utilization_synth.pb }
